## Hidden Layer with ReLU activation function
Below is an example of using the ReLU function to turn a linear single layer network into a non-linear multilayer network.

The code contains comments to undertand matric multiplications step by step

![](relu-network.png)

In [1]:
# Solution is available in the other "solution.py" tab
import tensorflow as tf

output = None
hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights), # For the hidden layer
    tf.Variable(out_weights)] # For the output layer
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[1.0, 2.0, 3.0, 4.0], [-1.0, -2.0, -3.0, -4.0], [11.0, 12.0, 13.0, 14.0]])

# Gives:
# [[  5.60000038   4.9000001    5.10000038]
#  [ -5.60000038  -4.9000001   -5.10000038]
#  [ 23.59999847  23.89999962  24.10000038]]
hidden_layer = tf.add(tf.matmul(features, weights[0]), biases[0])

# Gives:
# [[  5.60000038   4.9000001    5.10000038]
#  [  0.           0.           0.        ]
#  [ 23.59999847  23.89999962  24.10000038]]
hidden_layer = tf.nn.relu(hidden_layer) # Usage of ReLu


# Gives:
# [[  5.11000013   8.44000053]
#  [  0.           0.        ]
#  [ 24.01000214  38.23999786]]
output = tf.add(tf.matmul(hidden_layer, weights[1]), biases[1])

init = tf.global_variables_initializer()
with tf.Session() as session:
    session.run(init)
    out = session.run(output)
    print(out)

[[  5.10999966   8.43999958]
 [  0.           0.        ]
 [ 24.01000214  38.24000168]]
